get_filename_component(BRIEFCASE_CRYPTO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(USE_SHARED_MBEDTLS_LIBRARY OFF CACHE BOOL "" FORCE)
set(USE_STATIC_MBEDTLS_LIBRARY ON CACHE BOOL "" FORCE)
# Mbed TLS 3.6.7 still declares a 3.5.1 policy baseline. CMake 4 warns below 3.10.
# Use the documented third-party override, scoped to this dependency only.
function(briefcase_add_mbedtls)
  if(NOT DEFINED CMAKE_POLICY_VERSION_MINIMUM OR CMAKE_POLICY_VERSION_MINIMUM VERSION_LESS 3.10)
    set(CMAKE_POLICY_VERSION_MINIMUM 3.10)
  endif()
  add_subdirectory("${BRIEFCASE_CRYPTO_ROOT}/third_party/mbedtls-3.6.7" "${CMAKE_BINARY_DIR}/mbedtls" EXCLUDE_FROM_ALL)
endfunction()
briefcase_add_mbedtls()
foreach(t mbedcrypto mbedx509 mbedtls)
  target_compile_definitions(${t} PUBLIC MBEDTLS_USER_CONFIG_FILE="TlsConfig.h")
  target_include_directories(${t} PUBLIC "${BRIEFCASE_CRYPTO_ROOT}/runtime/Briefcase.Admin")
endforeach()
find_package(Threads REQUIRED)
add_library(Briefcase.Admin.Crypto STATIC "${BRIEFCASE_CRYPTO_ROOT}/runtime/Briefcase.Admin/Security.cpp")
target_link_libraries(Briefcase.Admin.Crypto PUBLIC mbedtls Threads::Threads)
target_compile_features(Briefcase.Admin.Crypto PUBLIC cxx_std_20)
