if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
  message(FATAL_ERROR "The experimental Linux server core currently supports x86_64 only.")
endif()
if(BRIEFCASE_LINUX_SERVER_HOST)
  message(STATUS "Building experimental Linux server host; client components excluded")
else()
  message(STATUS "Building Linux SERVER CORE and native launcher: no Unreal backend or client modules")
endif()
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
include(FetchContent)
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
FetchContent_Declare(json GIT_REPOSITORY https://github.com/nlohmann/json.git
  GIT_TAG 9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03)
set(ZYDIS_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_Declare(zydis GIT_REPOSITORY https://github.com/zyantific/zydis.git
  GIT_TAG 569320ad3c4856da13b9dbf1f0d9e20bda63870e)
FetchContent_MakeAvailable(json zydis)
add_library(Briefcase.ModApi INTERFACE)
target_include_directories(Briefcase.ModApi INTERFACE sdk/Briefcase.ModApi/include sdk/Briefcase.ClientModApi/include)
include(cmake/PortableCore.cmake)
add_library(Briefcase.Core STATIC ${BRIEFCASE_PORTABLE_CORE_SOURCES}
  runtime/Briefcase.NativeHost/NativeContract.cpp)
target_include_directories(Briefcase.Core PUBLIC runtime/Briefcase.NativeHost)
target_link_libraries(Briefcase.Core PUBLIC nlohmann_json::nlohmann_json Briefcase.ModApi Zydis)
add_library(Briefcase.Localization STATIC runtime/Briefcase.Localization/Catalog.cpp)
target_link_libraries(Briefcase.Localization PUBLIC Briefcase.Core)
include(cmake/AdminCrypto.cmake)
find_package(CURL 7.85 REQUIRED)
find_package(LibArchive REQUIRED)
add_library(Briefcase.ServerUpdate STATIC
  loader/Briefcase.ServerLauncher/LinuxFiles.cpp
  loader/Briefcase.ServerLauncher/LinuxDownload.cpp
  loader/Briefcase.ServerLauncher/Update.cpp)
target_link_libraries(Briefcase.ServerUpdate PUBLIC nlohmann_json::nlohmann_json
  PRIVATE CURL::libcurl LibArchive::LibArchive mbedcrypto)
target_include_directories(Briefcase.ServerUpdate PUBLIC loader/Briefcase.ServerLauncher)
add_executable(Briefcase.ServerLauncher loader/Briefcase.ServerLauncher/LinuxMain.cpp)
target_link_libraries(Briefcase.ServerLauncher PRIVATE Briefcase.ServerUpdate)
target_compile_definitions(Briefcase.ServerLauncher PRIVATE BRIEFCASE_FRAMEWORK_VERSION="${PROJECT_VERSION}")
add_library(Briefcase.Admin.Transport STATIC runtime/Briefcase.Admin/Transport.cpp
  runtime/Briefcase.Admin/PosixIdentity.cpp)
target_link_libraries(Briefcase.Admin.Transport PUBLIC Briefcase.Admin.Crypto)
add_executable(Briefcase.AdminTransportContracts tests/AdminTransportContracts.cpp)
target_link_libraries(Briefcase.AdminTransportContracts PRIVATE Briefcase.Admin.Transport)

add_library(Briefcase.Admin.Service STATIC runtime/Briefcase.Admin/Service.cpp
  runtime/Briefcase.Admin/PosixFiles.cpp runtime/Briefcase.Admin/Management.cpp
  runtime/Briefcase.Admin/PosixRestart.cpp runtime/Briefcase.NativeHost/Startup.cpp)
target_link_libraries(Briefcase.Admin.Service PUBLIC Briefcase.Admin.Transport Briefcase.Core Briefcase.Localization)
add_executable(Briefcase.AdminContracts tests/AdminContracts.cpp)
target_link_libraries(Briefcase.AdminContracts PRIVATE Briefcase.Admin.Service)

add_executable(Briefcase.AdminManagementContracts tests/AdminManagementContracts.cpp)
target_link_libraries(Briefcase.AdminManagementContracts PRIVATE Briefcase.Admin.Service)

add_executable(Briefcase.AdminPeerFixture tests/AdminPeerFixture.cpp)
target_link_libraries(Briefcase.AdminPeerFixture PRIVATE Briefcase.Admin.Service)
add_executable(Briefcase.AdminSetup tools/LinuxAdminSetup.cpp)
target_link_libraries(Briefcase.AdminSetup PRIVATE Briefcase.Admin.Service)

# Same educational sample as Windows, exercised by both contracts and the optional game host.
add_library(Briefcase.NativeHello SHARED samples/Briefcase.NativeHello/Hello.cpp)
target_link_libraries(Briefcase.NativeHello PRIVATE Briefcase.ModApi)
set_target_properties(Briefcase.NativeHello PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden)
add_executable(Briefcase.LinuxNativeContracts tests/LinuxNativeContracts.cpp)
target_link_libraries(Briefcase.LinuxNativeContracts PRIVATE Briefcase.Admin.Service)
enable_testing()
add_test(NAME LinuxNativeContracts COMMAND Briefcase.LinuxNativeContracts)
add_test(NAME AdminManagementContracts COMMAND Briefcase.AdminManagementContracts)
add_test(NAME AdminContracts COMMAND Briefcase.AdminContracts)
set_tests_properties(AdminContracts PROPERTIES TIMEOUT 60)
add_test(NAME AdminTransportContracts COMMAND Briefcase.AdminTransportContracts)
set_tests_properties(AdminTransportContracts PROPERTIES TIMEOUT 30)
foreach(pair "Contracts;NativeContracts" "ReflectionContracts;ReflectionContracts"
             "PortableServerContracts;PortableServerContracts" "LibraryContracts;LibraryContracts")
  list(GET pair 0 source)
  list(GET pair 1 test)
  add_executable(Briefcase.${source} tests/${source}.cpp)
  target_link_libraries(Briefcase.${source} PRIVATE Briefcase.Core Briefcase.Localization ${CMAKE_DL_LIBS})
  if(source STREQUAL "LibraryContracts")
    add_dependencies(Briefcase.${source} Briefcase.NativeHello)
    add_test(NAME ${test} COMMAND Briefcase.${source} "$<TARGET_FILE:Briefcase.NativeHello>")
  else()
    add_test(NAME ${test} COMMAND Briefcase.${source})
  endif()
endforeach()
add_executable(Briefcase.CAbi tests/Abi.c)
set_target_properties(Briefcase.CAbi PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON)
target_link_libraries(Briefcase.CAbi PRIVATE Briefcase.ModApi)
add_test(NAME CAbiContract COMMAND Briefcase.CAbi)
add_executable(Briefcase.AdminCryptoContracts tests/AdminCryptoContracts.cpp)
target_link_libraries(Briefcase.AdminCryptoContracts PRIVATE Briefcase.Admin.Crypto)
add_test(NAME AdminCryptoContracts COMMAND Briefcase.AdminCryptoContracts)
set_tests_properties(AdminCryptoContracts PROPERTIES TIMEOUT 30)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_test(NAME AdminTlsInterop COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/AdminInterop.py"
  "$<TARGET_FILE:Briefcase.AdminPeerFixture>")
set_tests_properties(AdminTlsInterop PROPERTIES TIMEOUT 45)
add_test(NAME SourcePublicationContracts COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/SourcePublicationContracts.py")
add_executable(Briefcase.LinuxUpdaterDriver tests/LinuxUpdaterDriver.cpp)
target_link_libraries(Briefcase.LinuxUpdaterDriver PRIVATE Briefcase.ServerUpdate)
add_test(NAME LinuxDownloadContracts COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/LinuxDownloadContracts.py")
add_test(NAME LinuxUpdaterContracts COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/LinuxUpdaterContracts.py" "$<TARGET_FILE:Briefcase.LinuxUpdaterDriver>")
add_test(NAME LinuxReleaseContracts COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tests/LinuxReleaseContracts.py")
# Production install/release packaging remains separate from this experimental build.

# Optional offline diagnostic. The caller supplies a separately built, pinned Linux
# patternsleuth_bind archive; this does not select a production Unreal backend.
set(BRIEFCASE_LINUX_SCANNER_LIBRARY "" CACHE FILEPATH "Experimental Linux patternsleuth_bind static library")
if(BRIEFCASE_LINUX_SCANNER_LIBRARY)
  if(NOT EXISTS "${BRIEFCASE_LINUX_SCANNER_LIBRARY}")
    message(FATAL_ERROR "Linux scanner library does not exist")
  endif()
  add_executable(Briefcase.LinuxUnrealScan tools/LinuxUnrealScan.cpp)
  target_link_libraries(Briefcase.LinuxUnrealScan PRIVATE nlohmann_json::nlohmann_json
    "${BRIEFCASE_LINUX_SCANNER_LIBRARY}" Threads::Threads ${CMAKE_DL_LIBS} m util rt)
  add_test(NAME LinuxUnrealScanContracts COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_SOURCE_DIR}/tests/LinuxUnrealScanContracts.py" "$<TARGET_FILE:Briefcase.LinuxUnrealScan>")
  set_tests_properties(LinuxUnrealScanContracts PROPERTIES TIMEOUT 60)
endif()
