include(FetchContent)
set(UE4SS_ROOT "${CMAKE_SOURCE_DIR}/third_party/RE-UE4SS")
if(NOT EXISTS "${UE4SS_ROOT}/deps/first/Unreal/src/UnrealInitializer.cpp")
  message(FATAL_ERROR "Run scripts/build/Fetch-Dependencies.ps1 first.")
endif()
option(BRIEFCASE_UE4SS_HEADLESS "Compile only the UE4SS Unreal engine and its dependencies" ON)
if(NOT BRIEFCASE_UE4SS_HEADLESS)
  message(FATAL_ERROR "This milestone only supports the headless backend.")
endif()
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
FetchContent_Declare(json GIT_REPOSITORY https://github.com/nlohmann/json.git GIT_TAG 9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03)
set(ZYDIS_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(ZYDIS_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_Declare(zydis GIT_REPOSITORY https://github.com/zyantific/zydis.git GIT_TAG 569320ad3c4856da13b9dbf1f0d9e20bda63870e)
FetchContent_MakeAvailable(json zydis)
set(ZYDIS_LIBRARY Zydis)
set(ZYCORE_LIBRARY Zycore)
get_target_property(ZYDIS_INCLUDE_DIR Zydis INCLUDE_DIRECTORIES)
get_target_property(ZYCORE_INCLUDE_DIR Zycore INCLUDE_DIRECTORIES)
set(POLYHOOK_BUILD_DLL ON CACHE BOOL "" FORCE)
set(POLYHOOK_BUILD_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(POLYHOOK_BUILD_STATIC_RUNTIME OFF CACHE BOOL "" FORCE)
set(POLYHOOK_USE_EXTERNAL_ZYDIS ON CACHE BOOL "" FORCE)
set(ASMJIT_STATIC ON CACHE BOOL "" FORCE)
FetchContent_Declare(polyhook2 GIT_REPOSITORY https://github.com/stevemk14ebr/PolyHook_2_0.git GIT_TAG fd2a88f09c8ae89440858fc52573656141013c7f)
FetchContent_MakeAvailable(polyhook2)
get_target_property(polyhook_includes PolyHook_2 INTERFACE_INCLUDE_DIRECTORIES)
set(clean_includes "")
foreach(dir IN LISTS polyhook_includes)
  if(IS_ABSOLUTE "${dir}")
    list(APPEND clean_includes "$<BUILD_INTERFACE:${dir}>")
  else()
    list(APPEND clean_includes "${dir}")
  endif()
endforeach()
set_property(TARGET PolyHook_2 PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${clean_includes}")
add_compile_definitions(UE_GAME UE_BUILD_SHIPPING PLATFORM_WINDOWS PLATFORM_MICROSOFT
  OVERRIDE_PLATFORM_HEADER_NAME=Windows UBT_COMPILED_PLATFORM=Win64
  RC_UNREAL_BUILD_STATIC RC_ASM_HELPER_BUILD_STATIC RC_FILE_BUILD_STATIC
  RC_DYNAMIC_OUTPUT_BUILD_STATIC RC_SINGLE_PASS_SIG_SCANNER_BUILD_STATIC RC_SINGLE_PASS_SIG_SCANNER_STATIC DISABLE_PROFILER)
add_library(Profiler INTERFACE)
target_include_directories(Profiler INTERFACE "${UE4SS_ROOT}/deps/first/Profiler/include")
foreach(module Constructs Helpers Function File DynamicOutput SinglePassSigScanner ASMHelper Unreal)
  add_subdirectory("${UE4SS_ROOT}/deps/first/${module}" "${CMAKE_BINARY_DIR}/ue4ss/${module}")
endforeach()
get_target_property(output_sources DynamicOutput SOURCES)
list(FILTER output_sources EXCLUDE REGEX "DebugConsoleDevice.cpp$")
set_property(TARGET DynamicOutput PROPERTY SOURCES "${output_sources}")
set(CARGO_TARGET "${CMAKE_BINARY_DIR}/cargo")
add_custom_command(OUTPUT "${CARGO_TARGET}/release/patternsleuth_bind.lib"
  COMMAND cargo build --locked --release --manifest-path "${UE4SS_ROOT}/deps/first/patternsleuth_bind/Cargo.toml" --target-dir "${CARGO_TARGET}"
  WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
  COMMENT "Building pinned UE4SS signature scanner")
add_custom_target(patternsleuth_build DEPENDS "${CARGO_TARGET}/release/patternsleuth_bind.lib")
add_library(patternsleuth_bind STATIC IMPORTED GLOBAL)
set_target_properties(patternsleuth_bind PROPERTIES IMPORTED_LOCATION "${CARGO_TARGET}/release/patternsleuth_bind.lib")
add_dependencies(patternsleuth_bind patternsleuth_build)
